### ISSUE TITLE
Recent Update Pushed UI off to the side

### ISSUE THREAD

**Issue by Dorkington** [tonycpsu/bluesky-navigator#4]
See below

<img width="838" height="1294" alt="Image" src="https://github.com/user-attachments/assets/ddd1610b-0b66-4ac0-b6bb-3689468d8ebb" />

**Comment by Dorkington** [comment]
If I select the option, "hide side right sidebar" it moves the main feed back to where it's supposed to be

Edit: Nevermind, soon as I resized the window it broke again

macOS/Firefox

**Comment by tonycpsu** [comment]
Should be fixed with the most recent update.

**Comment by Dorkington** [comment]
Unfortunately it's still the same for me, pushed off to the side, even with default settings selected (below is hidden right side bar, and still pushed off to the side)

<img width="1105" height="1001" alt="Image" src="https://github.com/user-attachments/assets/565f7276-d30e-4d4d-a231-19de07d1d792" />

If I set my view percent to 90% in Firefox, it all aligns correctly, if that is helpful at all?

**Comment by tonycpsu** [comment]
is the latest update any better?

**Comment by Dorkington** [comment]
Yes! Thank you so much!
